name: Sample Workflow Dispatch
run-name: Sample Workflow Dispatch
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment will run the dbt steps."
        type: choice
        options:
        - dev
        - test
        - prod
        required: true

jobs:
  DBT_DEPLOY:
    runs-on: [ubuntu-latest]
    timeout-minutes: 720

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
        
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Grant permission to execute scripts
        run: chmod +x .github/scripts/*
      
      - name: Check usage of empty vars
        run: .github/scripts/vars_usage.sh
        env:
          environment: ${{ env.environment }}
          environment2: ${{ inputs.environment }}