name: Sample Workflow
run-name: Sample Workflow
on: 
  push:
    branches:
      - main

jobs:
  DBT_DEPLOY:
    runs-on: [ubuntu-latest]
    timeout-minutes: 720

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: CHeck usage of empty vars
        run: ./scripts/use_vars.sh
        env:
          environment: ${{ env.environment }}
          environment2: ${{ inputs.environment }}